### ISSUE TITLE
Update DOI UI app to use NPM package

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/doi-ui#106]

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo removes the old search code and will add the npm package version of the search code.

**Comment by tloubrieu-jpl** [comment]
The change is done and @eddiesarevalo is now testing.

**Comment by eddiesarevalo** [comment]
@tloubrieu-jpl After some more testing I did discover some bugs. 
1) Hovering over status will crash the app. A popup is supposed to show but something must be causing an error.
2) Going to the search page will cause the app bar to become white. There must be some sort of styling issue.

**Comment by eddiesarevalo** [comment]
@tloubrieu-jpl Will put this ticket in review and create a new one for bug fixes.

**Comment by eddiesarevalo** [comment]
Fixed the known bugs will continue to test before closing this one.

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo you should have created a pull request in the nasa-pds/doi-ui repository to formalize the update and enable the review of the changes.

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo are the changes in `pds-wds-install` branch ?

**Comment by gxtchen** [comment]
@jordanpadams @tloubrieu-jpl How can I verify this is done in B12.1?

**Comment by jordanpadams** [comment]
@gxtchen just updated this to skip I&T
