### ISSUE TITLE
when a single result is searched it does not show in the list ?

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/doi-ui#122]
## 🐛 Describe the bug

In a local deployment I am getting this result for a search:
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/60993872/157786857-662a7b68-9f21-499a-b0bf-1d2986ab9cca.png">

The API search request is:
http://localhost:8080/PDS_APIs/pds_doi_api/0.2/dois?ids=*insight_cameras%3A%3A5.0*

gives the following result:
```
[
  {
    "doi": "10.13143/a2t9-za69",
    "identifier": "urn:nasa:pds:insight_cameras::5.0",
    "node": "eng",
    "status": "draft",
    "submitter": "loubrieu@jpl.nasa.gov",
    "title": "Laboratory Shocked Feldspars Collection #1",
    "update_date": "2022-03-11T00:38:48+00:00"
  }
]

```
## 📜 To Reproduce
1. Go to 'ui' search
2. Search for a string which returns a single result
3. See error saying 1 result is found but not showing it in the table

## 🕵️ Expected behavior

The result should show in the table.

## 📚 Version of Software Used

latest version on main branch

## 🖥 System Info

---

**Comment by tloubrieu-jpl** [comment]
Actually it is not because of the single result because now I can see a single result, see screenshot 
<img width="877" alt="image" src="https://user-images.githubusercontent.com/60993872/157936231-5e5a0b16-1992-4df5-bd64-f37d62ab97b3.png">

The cause might be the status a this single result which was only reserved when I first made the search.

I am thinking the bug might be a discrepancy between the way the number of rows is counted and the rows which are actually displayed.

**Comment by eddiesarevalo** [comment]
@tloubrieu-jpl I wasn't able to reproduce this one. The value that you pointed out will return an empty array. When I try to to get a different single value it will show. Also to test I hard coded the response:
`[  {    "doi": "10.13143/a2t9-za69",    "identifier": "urn:nasa:pds:insight_cameras::5.0",    "node": "eng",    "status": "draft",    "submitter": "loubrieu@jpl.nasa.gov",    "title": "Laboratory Shocked Feldspars Collection #1",    "update_date": "2022-03-11T00:38:48+00:00"  }]`
And it will still show that single value. 

Maybe there was a different kind of error that occured for you in that image?

**Comment by eddiesarevalo** [comment]
@tloubrieu-jpl l did a lot more testing but I still can't reproduce this one. Are you still getting this? If not maybe we can close this one?

**Comment by tloubrieu-jpl** [comment]
We are closing this ticket because we are not able to reproduce
