### ISSUE TITLE
Null error message stays in a release/update scenario

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/doi-ui#123]
## 🐛 Describe the bug
See video

https://user-images.githubusercontent.com/60993872/157935510-faa73c91-df92-4e84-80e1-7fdee0cb8827.mov

## 📜 To Reproduce
1. Go to '.release a doi'
2. Input the url of a test dataset with warning in it for example, 
[bundle_5.0.xml.zip](https://github.com/NASA-PDS/doi-ui/files/8234698/bundle_5.0.xml.zip)

3. Uncheck the ignore warning button
4. Click on button upload label
5. Warning shows
6. Click on checkbox 'ignore warning'
7. The submission works well but a message with null description stays

<img width="614" alt="image" src="https://user-images.githubusercontent.com/60993872/157934007-5187ba6a-c7e2-45d7-97f6-884a5ce02042.png">

## 🕵️ Expected behavior

The error message should not be here

## 📚 Version of Software Used

Latest version of UI with latest version of UI deployed on pds-dev3 (from branch [fix_api_for_ui](https://github.com/NASA-PDS/doi-service/tree/fix_api_for_ui))

## 🖥 System Info

---

**Comment by eddiesarevalo** [comment]
@tloubrieu-jpl I am unable to reproduce this one completely with the bundle.xml file. If I deploy the bundle locally the server is unable to retrieve it from my computer so it will always return an error. Do you have an example of a working one that I can try to get a success message?

**Comment by tloubrieu-jpl** [comment]
Example of URL with a PDS4 bundle: https://pds-imaging.jpl.nasa.gov/data/nsyt/insight_cameras/bundle_6.0.xml

**Comment by eddiesarevalo** [comment]
@tloubrieu-jpl This pds4 bundle URL gives me this error:
![Screen Shot 2022-03-21 at 1.03.03 PM.png](https://images.zenhubusercontent.com/5e98a8928301b57ff5d93d52/1c66514f-7185-4ec8-a95c-3768fb019689)
Maybe in the next break out we can take a look at this one? I just need one that will give me a success message.
