### ISSUE TITLE
Error and warning message width should match with the rest of the form

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/doi-ui#125]
## 🐛 Describe the bug

See video here with an example of a very wide message 

https://user-images.githubusercontent.com/60993872/158233062-387b7174-127d-47cd-8aa9-2323eb855954.mov

## 🕵️ Expected behavior

The width of the error or warning box should be aligned with the rest of the form

## 🖥 System Info

---

**Comment by eddiesarevalo** [comment]
@tloubrieu-jpl I'm not sure how you got a super long no break string but I simulated it by hard coding an error with a long string. I added a css style to break the string if it doesn't fit. So it won't show a long div anymore.

**Comment by tloubrieu-jpl** [comment]
That will be perfect, thanks @eddiesarevalo.
