### ISSUE TITLE
App bar slightly broken when DOI UI is deployed from build package with `serve`

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/doi-ui#132]
## 🐛 Describe the bug

See screenshot 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/60993872/163893790-934f1cb6-5737-422c-afd8-af2419b232e1.png">

## 🖥 System Info

---

**Comment by jordanpadams** [comment]
To be discussed at the breakout. More complicated than it sounds

**Comment by tloubrieu-jpl** [comment]
We decided to remove the app bar from the application since eventually the application will be integrated in a frameward (e.g. drupal) which has its own header/menus...

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo set the theme-provider in the DOI-UI and remove the app bar.
