### ISSUE TITLE
Update Vulnerable Dependencies

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/doi-ui#139]
We should update these vulnerabilities as soon as the updates are available.

These might affect us but there is no current update available.
- [ ] https://github.com/NASA-PDS/doi-ui/security/dependabot/9

These won't affect us since they are not exposed after the build process but we should still update as soon as possible. 
- [ ] https://github.com/NASA-PDS/doi-ui/security/dependabot/12
- [ ] https://github.com/NASA-PDS/doi-ui/security/dependabot/14
- [ ] https://github.com/NASA-PDS/doi-ui/security/dependabot/29
- [ ] https://github.com/NASA-PDS/doi-ui/security/dependabot/30

The full descriptions of these are at #137

**Comment by tloubrieu-jpl** [comment]
This ticket is obsolete since we have now more vulnerability to fix and more dependencies to upgrade.
