### ISSUE TITLE
Deploy DOI UI on pds-gamma

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/doi-ui#141]
## 💡 Description

Spin up latest DOI UI at pds.nasa.gov/engineering/dois/editor . See https://wiki.jpl.nasa.gov/display/PDSEN/DOI+UI+Installation+and+Deployment for details

Note: Rationale for Ops Team performing this deployment is it a webpage deployment, not a service deployment, and Ops Team owns the website management.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl what do you think of the URL?

**Comment by c-suh** [comment]
Have let the interested parties know so they can verify first part is deployed correctly. Also created [a ticket](https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-1934) for the SAs with the information from the [documentation](https://wiki.jpl.nasa.gov/display/PDSEN/DOI+UI+Installation+and+Deployment#DOIUIInstallationandDeployment-SetupAuthenticationthroughApacheHTTPServer).

**Comment by tloubrieu-jpl** [comment]
We are waiting for update frmo the SA's on the ticket

**Comment by tloubrieu-jpl** [comment]
@c-suh The version of the doi-service need to be updated on pds-gamma, the latest stable version is https://github.com/NASA-PDS/doi-service/releases/tag/v2.2.0

**Comment by tloubrieu-jpl** [comment]
The deployment works on https://pds-gamma.jpl.nasa.gov/tools/doi-editor after @c-suh  upgraded the doi-service and Andrew changed the configuration of the proxy in frount of the doi-service. See https://pds-gamma.jpl.nasa.gov/tools/doi-editor
