### ISSUE TITLE
Deploy doi-ui in production on AWS

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/doi-ui#143]
## 💪 Motivation
...so that it can be used for real.

## 📖 Additional Details

- The ui should use the doi-service in production as a back-end.
- We should ask a different password than on pds-gamma to set the basic authentication on the doi-service and the doi-ui, so that a user can not by mistake create DOI in production.

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by c-suh** [comment]
@tloubrieu-jpl and @jordanpadams the documentation says to update the API endpoint to an absolute URL on gamma, but I'm assuming this should be relative so that they point to their respective databases. Please let me know if this isn't the case.

**Comment by c-suh** [comment]
The DOI-UI has been deployed, and the search has been tested for connection to the production database. The request for access authentication has been submitted with the SAs [here](https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-1963), with information from the ticket for gamma and the distinction of a different password for production (2nd bullet point in Additional Details in the main description).

**Comment by jordanpadams** [comment]
@c-suh sorry for the lack of clarity here. definitely set a relative path here. also, we do not want to distribute the ops password to anyone outside of EN until we have folks beta test the version on gamma

**Comment by c-suh** [comment]
jordanpadams no worries. I went ahead with the relative path and updated the documentation as well. Heard about the ops password (which is still TBD) - keep it internal until I get the green light from you or Thomas or Vivian.

Side note: deployed versions are
- v2.2.0 for Service
- v1.0.0 for UI

**Comment by c-suh** [comment]
SA provided a new password but it does not work. Have responded on the SA ticket.

**Comment by c-suh** [comment]
It's working! A few last details are being worked out regarding accessibility outside the firewall.

**Comment by tloubrieu-jpl** [comment]
I will close this ticket and open a new one to complete what remains to be done for the publication outside JPL VPN:

- replace authentication with Cognito on ui and service
- create an ASR for the application
- do a security scan
