### ISSUE TITLE
DOI UI Menu jump

### ISSUE THREAD

**Issue by gxtchen** [NASA-PDS/doi-ui#144]
## 🐛 Describe the bug identified during I&T
Switching between the Home and Search button, the style of the menu bar starts to jump after 5 to 6 clicks. Keep going for a few more clicks will see the menu bar becomes white, and refreshing the screen doesn't fix it.

## 🥼 Related Test Case(s)
Test Release build 12.1

## 🔁 : Related issues
https://github.com/NASA-PDS/doi-ui/issues/117

### 📜 To Reproduce
1. Go to DOI UI
2. Click on Search and back to Home for several times.

### 🕵️ Expected behavior
Style of the page should stay intact.

**Comment by viviant100** [comment]
Bug fixed and will be merged to release in B12.1.  Work is captured in https://github.com/NASA-PDS/doi-ui/issues/132.
