### ISSUE TITLE
Upgrade deployment of DOI UI to patched v1.0.1

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/doi-ui#146]

**Comment by c-suh** [comment]
Done on gamma and production. Lightly tested on production (search and viewing information with 'Update' on the Release page but without actually submitting any changes) but not on gamma since that is 500.

**Comment by c-suh** [comment]
SAs have fixed gamma and it is also ready for review.

**Comment by c-suh** [comment]
@tloubrieu-jpl the new zip from https://github.com/NASA-PDS/doi-ui/releases/tag/v1.0.1 still has the app-bar in it and does not say the version number in the unzipped directory. Additionally, per the discussed deployment location (step 2 of [Install](https://wiki.jpl.nasa.gov/display/PDSEN/DOI+UI+Installation+and+Deployment#DOIUIInstallationandDeployment-Install)), I was not able to create a new folder for 'applications' nor move the existing legacy folder. For now, I placed it inside the legacy folder and symlinked it (per step 3 of the same section).

**Comment by c-suh** [comment]
@tloubrieu-jpl no worries! This has been deployed to production and gamma. The deployment/installation location is being discussed with the SAs (read [here](https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-2014)), which I will fill you in on at tomorrow's meeting.
