### ISSUE TITLE
When authentication is not valid anymore, need to make a different message than when the API is down.

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/doi-ui#159]
When the back-end API is not reachable because authentication became invalid we need a different message than when the API is not reachable.

I think during the test we need to catch specific status (401 or 403) and make a new message saying "your authentication is not valid anymore, please reload and create a new session".

To reproduce the current error:
1. login on the pds-gamma instance https://pds-gamma.jpl.nasa.gov/tools/doi-editor
2. wait for 5+ minutes until the session expires
3. create a DOI from an online PDS4 label
4. you should see that:
![image](https://user-images.githubusercontent.com/60993872/180286010-b32fbc17-c45c-4242-944a-5f2dea7ebb7a.png)

**Comment by jimmie** [comment]
@ramesh-maddegoda is helping out w/ this. Eddie waiting on this.

**Comment by jordanpadams** [comment]
Status: @ramesh-maddegoda 95% complete for server and client side updates. also has auto-refresh token functionality which is valid for 30 days. we can set a flag in the library to handle this for us. only remaining thing is to fix logout functionality

**Comment by ramesh-maddegoda** [comment]
The changes related with application level authentication (with Cognito ) in doi-ui is completed and I made  a pull request at https://github.com/NASA-PDS/doi-ui/pull/163

**Comment by ramesh-maddegoda** [comment]
Merged changes
