### ISSUE TITLE
When the user wants to update a DOI he's asked again if the data is publicly available

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/doi-ui#89]
## 🐛 Describe the bug

When the user wants to update a DOI he's asked again if the data is publicly available

## 📜 To Reproduce
See video

https://user-images.githubusercontent.com/60993872/136121266-717e402b-45c0-496e-826c-35828f8bc04d.mov

## 🕵️ Expected behavior

The data is already publicly available, does that make sense to ask the question again ?

## 🖥 System Info

---

**Comment by jordanpadams** [comment]
closing as wontfix. expected functionality.
