### ISSUE TITLE
As a user, I want to get an error message with support contact when the backend API is unavailable

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/doi-ui#92]
## 💪 Motivation
...so that I understand more or less wht is happening and that I can report the issue to pdsen operators

## 📖 Additional Details

The message could be something like:

"We were not able to process your request, please try again later or contact  pds-operator@jpl.nasa.gov"

## ⚖️ Acceptance Criteria
**Given** the backend API is not available
**When I perform** search or any type of operations involving the request to the API (reserve, update/release)
**Then I expect** a popup message signifying the failure to the user and providing a point of contact to reach for support.

**Comment by jordanpadams** [comment]
@eddiesarevalo @tloubrieu-jpl where are we at with this issue? is this a lien on TRR or something we can push to some point build in the B13.0 release plan?

**Comment by tloubrieu-jpl** [comment]
@jordanpadams @eddiesarevalo is working on it now. It is not critical for release 12.1 but I might be able to have it in the stable release which I am planning to do this week.
